#SPDX-License-Identifier: MIT-0
---
# tasks file for ansible-role-fullstack-deploy
- name: install dependencies
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop:
    - nodejs
    - npm
    - nginx

- name: Copy application files
  copy:
    src: app/
    dest: /var/www/todo-app/
    owner: root
    group: root
    mode: '0755'
    
- name: Install app dependencies
  command: npm install
  args:
    chdir: /var/www/todo-app/

- name: Copy systemd service file
  template:
    src: todo.service.j2
    dest: /etc/systemd/system/todo.service


- name: Start app service
  systemd:
    name: todo
    enabled: true

    state: started
- name: Copy nginx config
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/sites-available/todo
    
- name: Enable nginx config
  file:
    src: /etc/nginx/sites-available/todo
    dest: /etc/nginx/sites-enabled/todo
    state: link
    force: true

- name: Restart nginx
  service:
    name: nginx
    state: restarted